package com.zsx.web.entity;
// Generated 2014-6-27 15:52:44 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Tuser generated by hbm2java
 */
@Entity
@Table(name = "user")
public class Tuser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
//	@GeneratedValue(generator = "zhaoshuxue")
//	@GenericGenerator(name = "zhaoshuxue", strategy = "uuid")
	@Column(name = "ID", nullable = false, length = 36)
	private String id;
	
	
	@Column(name = "NAME")
	private String name;
	
	@Column(name = "PWD")
	private String pwd;
	
	public Tuser() {
	}

	public Tuser(String id) {
		this.id = id;
	}

	public Tuser(String id, String userName, String passWord) {
		this.id = id;
		this.name = userName;
		this.pwd = passWord;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}



}
